[package]
name = "logly"
version = "0.1.1"
description = "Rust Powered Python Logging Utility"
edition = "2021"
license = "MIT"
readme = "README.md"

[lib]
name = "_logly"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "ansi", "env-filter"] }
tracing-appender = "0.2.3"
once_cell = "1.19.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
chrono = { version = "0.4", features = ["serde"] }
